---
#---Acesso ao host do Vagrant
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant

common_packages_debian_like:
  - vim
  - build-essential
  - wget 
  - curl
  - net-tools
  - nano
  
#---Password para o MariaDB
mysql_root_password: root
mysql_zabbix_password: zabbix


...