---
- name: Instala o python caso o host não possua.
  hosts: remotos
  gather_facts: yes

  pre_tasks:
  - block:
    - name: 'Atualiza o cache dos repositórios (Familia Debian)'
      raw: "apt update"

    - name: 'Instala o python (Familia Debian)'
      raw: "apt install python -y"
    
    # become: yes
    # become_method: enable
    when: ansible_os_family == 'Debian'

  - block:
    - name: 'Limpa cache antigo dos repos (Familia RedHat)'
      raw: "dnf clean all"

    # - name: 'Atualiza os repo no Centos'
    #   raw: "dnf check-update"

    # - name: 'Instala o Python (Familia RedHat)'
    #   raw: "dnf install python -y"

    when: ansible_os_family == "RedHat"


